- hosts: app
  become: true

  vars:
    app_dir: /opt/aws-study
    app_file: app.war

  tasks:
    - name: swapfile exists?
      stat:
        path: /swapfile
      register: swapfile_stat

    - name: create swap file
      command: fallocate -l 2G /swapfile
      when: not swapfile_stat.stat.exists

    - name: set swapfile permission
      file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: format swap
      command: mkswap /swapfile
      when: not swapfile_stat.stat.exists

    - name: check active swaps
      command: swapon --show
      register: swap_status
      changed_when: false

    - name: enable swap
      command: swapon /swapfile
      when: "'/swapfile' not in swap_status.stdout"

    - name: persist swap
      lineinfile:
        path: /etc/fstab
        line: "/swapfile swap swap defaults 0 0"
        state: present

    - name: install java-21
      dnf:
        name:  java-21-amazon-corretto-devel.x86_64
        state: present

    - name: install git
      dnf:
        name:  git
        state: present

    - name: clone repository
      become_user: ec2-user
      git:
        repo: https://github.com/koujienami/aws-study.git
        dest: /home/ec2-user/aws-study
        force: yes

    - name: change mode
      file:
        path: /home/ec2-user/aws-study/gradlew
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: build app
      become_user: ec2-user
      command: ./gradlew bootWar
      args:
        chdir: /home/ec2-user/aws-study

#    - name: stop existing bootRun
#      become_user: ec2-user
#      shell: pkill -f 'java.*aws-study|gradlew bootRun'
#      failed_when: false

#    - name: start bootRun
#      become_user: ec2-user
#      shell: nohup ./gradlew bootRun > bootrun.log 2>&1 </dev/null &
#      args:
#        chdir: /home/ec2-user/aws-study

    - name: find war file
      find:
        paths: /home/ec2-user/aws-study/build/libs
        patterns: "*.war"
        excludes: "*plain.war"
        file_type: file
      register: war_files

    - name: No war file
      fail:
        msg: "War file was not found"
      when: war_files.matched == 0

    - name: create app dir
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: copy war file
      copy:
        src: "{{ war_files.files[0].path }}"
        dest: "{{ app_dir }}/{{ app_file }}"
        remote_src: true
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: create systemd service file
      template:
        src: aws-study.service.j2
        dest: /etc/systemd/system/aws-study.service

    - name: reload systemd
      systemd:
        daemon_reload: true

    - name: enable aws-study service
      systemd:
        name: aws-study
        enabled: true

    - name: restart aws-study service
      systemd:
        name: aws-study
        state: restarted

    - name: wait for app port
      wait_for:
        port: 8080
        host: 127.0.0.1
        delay: 3
        timeout: 60 
