name: terraform-aws-deploy

on:
  pull_request:
    paths:
      - 'projects/terraform-aws-deploy/tf/**/*.tf'
      - 'projects/terraform-aws-deploy/tf/tests/**/*.tftest.hcl'
      - '.github/workflows/*.yaml'
      - '.github/workflows/*.yml'

  push:
    branches:
      - main
      - test2 #後で消す
    paths:
      - 'projects/terraform-aws-deploy/tf/**/*.tf'
      - 'projects/terraform-aws-deploy/tf/tests/**/*.tftest.hcl'
      - '.github/workflows/*.yaml'
      - '.github/workflows/*.yml'


permissions:
  contents: read
  id-token: write

env:
  TF_DIR: projects/terraform-aws-deploy/tf
  AWS_REGION: ap-northeast-1
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  plan:
    name: terraform CI/CD
    if: github.event_name == 'pull_request' || github.event_name == 'push' #pushは後で消す
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select -or-create dev

      - name: Fmt Check
        run: terraform fmt -check

      - name: Validate
        run: terraform validate


      - name: test
        run: terraform test -verbose

      - name: Plan
        run: terraform plan -no-color -input=false


  apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select -or-create prod

      - name: Apply
        run: terraform apply -auto-approve -input=false